# Small font_size will make text looks like blured/prydown
font_size:
  min: 5
  max: 10

# choose Text color range
# color boundary is in R,G,B format
font_color:
  enable: false
  black:
    fraction: 0.45
    l_boundary: [0,0,0]
    h_boundary: [30,30,30]
  white:
    fraction: 0.05
    l_boundary: [200,200,200]
    h_boundary: [255,255,255]
  blue:
    fraction: 0.20
    l_boundary: [0,0,150]
    h_boundary: [60,60,255]
  brown:
    fraction: 0.10
    l_boundary: [139,70,19]
    h_boundary: [160,82,43]
  green:
    fraction: 0.05
    l_boundary: [0,150,0]
    h_boundary: [60,255,60]
  red:
    fraction: 0.15
    l_boundary: [150,0,0]
    h_boundary: [255,60,60]

# By default, text is drawed by Pillow with (https://stackoverflow.com/questions/43828955/measuring-width-of-text-python-pil)
# If `random_space` is enabled, some text will be drawed char by char with a random space
random_space:
  enable: true
  fraction: 0.1
  min: -0.05 # -0.1 will make chars very close or even overlapped
  max: 0.1

# Do remap with sin()
# Currently this process is very slow!
curve:
  enable: true
  fraction: 0.4
  period: 360  # degree, sin 函数的周期
  min: 1 # sin 函数的幅值范围
  max: 5

# random crop text height
crop:
  enable: true
  fraction: 0.3

  # top and bottom will applied equally
  top:
    min: 1
    max: 4 # in pixel, this value should small than img_height
  bottom:
    min: 1
    max: 4 # in pixel, this value should small than img_height

# Use image in bg_dir as background for text
img_bg:
  enable: true
  fraction: 0.3

# Not work when random_space applied
text_border:
  enable: true
  fraction: 0.05

  # lighter than word color
  light:
    enable: true
    fraction: 0.5

  # darker than word color
  dark:
    enable: true
    fraction: 0.5

# https://docs.opencv.org/3.4/df/da0/group__photo__clone.html#ga2bf426e4c93a6b1f21705513dfeca49d
# https://www.cs.virginia.edu/~connelly/class/2014/comp_photo/proj2/poisson.pdf
# Use opencv seamlessClone() to draw text on background
# For some background image, this will make text image looks more real
seamless_clone:
  enable: true
  fraction: 0.4

perspective_transform:
  enable: true
  fraction: 0.6
  max_x: 30
  max_y: 30
  max_z: 10

blur:
  enable: true
  fraction: 0.2

# If an image is applied blur, it will not be applied prydown
prydown:
  enable: true
  fraction: 0.999
  max_scale: 2.5 # Image will first resize to 1.5x, and than resize to 1x

noise:
  enable: true
  fraction: 0.1

  gauss:
    enable: true
    fraction: 0.25

  uniform:
    enable: true
    fraction: 0.35

  salt_pepper:
    enable: true
    fraction: 0.15

  poisson:
    enable: true
    fraction: 0.25

line:
  enable: true
  fraction: 0.01

  under_line:
    enable: true
    fraction: 0.8

  table_line:
    enable: true
    fraction: 0.1

  middle_line:
    enable: true
    fraction: 0.1

line_color:
  enable: true
  white:
    fraction: 0.40
    l_boundary: [200,200,200]
    h_boundary: [255,255,255]
  black:
    fraction: 0.40
    l_boundary: [0,0,0]
    h_boundary: [64,64,64]
  blue:
    fraction: 0.20
    l_boundary: [0,0,150]
    h_boundary: [60,60,255]

# These operates are applied on the final output image,
# so actually it can also be applied in training process as an data augmentation method.

# By default, text is darker than background.
# If `reverse_color` is enabled, some images will have dark background and light text
reverse_color:
  enable: true
  fraction: 0.5

emboss:
  enable: true
  fraction: 0.1

sharp:
  enable: true
  fraction: 0.1

